name: Run CI and potentially release
on:
  pull_request:
  push:
    branches-ignore: [gh-pages]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.13.1'
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: ./bin/setup.sh
      - run: ./bin/generate-site.sh
      - name: Upload static site
        uses: peaceiris/actions-gh-pages@v2.10.1
        if: github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./site/dist/
        with:
          emptyCommits: false
          commitMessage: "${{ github.event.head_commit.message }} [skip ci]"
